### ISSUE TITLE
Error: no such file or directory, stat 'android/app/src/main/java/MainActivity.java'

### ISSUE THREAD

**Issue by maxfloden** [ionic-team/trapeze#109]
I get this error when running `npx trapeze run trapeze.config.yaml --android-project android --ios-project ios/App`

Output:
```
run ios bundleId com.xxx.yyy
run ios version 2.3.0
run ios incrementBuild 
run android packageName com.xxx.yyy
Fatal error: Error running command
[Error: ENOENT: no such file or directory, stat 'android/app/src/main/java/MainActivity.java'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'android/app/src/main/java/MainActivity.java'
}
```

My yaml file:
```
vars:
  BUNDLE_ID:
    default: com.xxx.yyy
  VERSION:
    default: 2.3.0
platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        version: $VERSION
        incrementBuild: true
  android:
    packageName: $BUNDLE_ID
    versionName: $VERSION
    incrementVersionCode: true
```

* @trapezedev/configure 5.0.6
* Ionic6 / Capacitor4 project

The MainActivity.java seems to be located in android/app/src/main/java/com/xxx/yyy/MainActivity.java - ie the bundle/package id is part of path.

I cannot find anywhere in the documentation how to specify the file location, so my guess is that it is supposed to work without specifying it?

**Comment by Marius-Romanus** [comment]
the same thing happens to me, it seems that it only happens when the variables are used

**Comment by maxfloden** [comment]
> the same thing happens to me, it seems that it only happens when the variables are used

@Marius-Romanus I tried without variables and noticed no difference

**Comment by mlynch** [comment]
The package rename stuff is a bit complicated and relies on your source layout matching what you have in the package attribute in your manifest file. I'm working on some logging stuff right now that will make this easier to debug, more info soon

**Comment by mlynch** [comment]
Just publised 6.0.1 of `@trapezedev/configure`, could you try that and run with `--verbose` to see the logging of the package operation?

Example:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/11214/201970322-f3770db9-1661-47e5-a7a6-4314495d4a7e.png">

**Comment by mlynch** [comment]
Closing for now until I get more info, thanks

**Comment by jaufgang** [comment]
@mlynch, I think the problem may be related to the recent deprecation of the `package` attribute in the manifest file in favour of using the `namespace` property in the module-level `build.gradle` 

Android Studio Upgrade Assistant has started prompting developers to allow it to automatically make this change:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/1747254/205739028-baab73fe-2162-4f3b-890e-1c9c9a7df721.png">

It looks like Trapeze will need to support using the `namespace` property, both for reading the old value and for updating to the new value.

**Comment by jaufgang** [comment]
While we're here, can we get the empty folders cleaned up (i.e. deleted) when they're left behind after moving the `MainActivity.java` file?

**Comment by mlynch** [comment]
Done in #145

**Comment by maxfloden** [comment]
Hi, 

I am revisiting this after upgrading from @trapezedev/configure 5.0.6 to 7.0.8 but  still get the same error/problem.
See below with `--verbose` flag

```
npx trapeze run trapeze.config.yaml --verbose
[log] xml(load) at android/app/src/main/AndroidManifest.xml
[log] xml(load) Found root namespaces in XML file: http://schemas.android.com/apk/res/android
run android packageName com.xxx.yyy
[log] android(setPackageName) setting Android package name to com.xxx.yyy from 
[log] gradle(setNamespace) to com.xxx.yyy in android/app/build.gradle
[log] gradle(parse) running Gradle parse with Java path java
[log] gradle(parse) read gradle file at android/app/build.gradle
[log] android(setPackageName) set manifest package attribute and applicationId to com.xxx.yyy
[log] xml(setAttrs) at android/app/src/main/AndroidManifest.xml - manifest/application/activity
[log] android(setPackageName) set <activity android:name="com.xxx.yyy.MainActivity"
[log] android(setPackageName) Got main activity name MainActivity.java
[log] android(setPackageName) Looking for old activity file at android/app/src/main/java/MainActivity.java
Fatal error: Error running command
[Error: ENOENT: no such file or directory, stat 'android/app/src/main/java/MainActivity.java'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'android/app/src/main/java/MainActivity.java'
}
```
