### ISSUE TITLE
Unable to update xml attributes

### ISSUE THREAD

**Issue by vscaiceanu-1a** [ionic-team/trapeze#87]
Hello,

This issue is related to https://github.com/ionic-team/trapeze/issues/78

I am trying to update the resources in `strings.xml`. using version `4.0.0-next.2`.

I tried several ways:

1. using `merge`

```yaml
 android:
    xml:
      - file: app/src/main/res/values/strings.xml
        target: resources
        merge: |
          <string name="app_name">$PRODUCT_NAME</string>
          <string name="title_activity_main">$PRODUCT_NAME</string>
          <string name="package_name">$ANDROID_PACKAGE_NAME</string>
          <string name="custom_url_scheme">$ANDROID_PACKAGE_NAME</string>
```
In this case there is no update. I still have the old values.

2.  using `inject`

```yaml
 android:
    xml:
      - file: app/src/main/res/values/strings.xml
        target: resources
        inject: |
          <string name="app_name">$PRODUCT_NAME</string>
          <string name="title_activity_main">$PRODUCT_NAME</string>
          <string name="package_name">$ANDROID_PACKAGE_NAME</string>
          <string name="custom_url_scheme">$ANDROID_PACKAGE_NAME</string>
```
I ended up with 8 entries (both old and new values)

3. using `delete` and `inject`

```yaml
 android:
    xml:
      - file: app/src/main/res/values/strings.xml
        delete: resources
      - file: app/src/main/res/values/strings.xml
        target: resources
        merge: |
          <string name="app_name">$PRODUCT_NAME</string>
          <string name="title_activity_main">$PRODUCT_NAME</string>
          <string name="package_name">$ANDROID_PACKAGE_NAME</string>
          <string name="custom_url_scheme">$ANDROID_PACKAGE_NAME</string>
```
Same result as 2. 

4. targeting by attribute as suggested in the [docs](https://trapeze.dev/docs/configuration-tool#xml)

```yaml
 android:
    xml:
      - resFile: values/strings.xml
        target: resources/string[@name="app_name"]
        replace: |
          <string name="app_name">$PRODUCT_NAME</string>
```

Getting an error:
```
Fatal error: Error running command
TypeError: Cannot read properties of null (reading 'parentNode')
    at _insertBefore (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/project/node_modules/@xmldom/xmldom/lib/dom.js:642:20)
    at Element.insertBefore (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/project/node_modules/@xmldom/xmldom/lib/dom.js:449:10)
    at /Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/project/dist/xml.js:140:30
    at Array.forEach (<anonymous>)
    at XmlFile.replaceFragment (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/project/dist/xml.js:135:15)
    at execute (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/configure/dist/operations/android/xml.js:36:27)
    at async executeOperations (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/configure/dist/tasks/run.js:74:10)
    at async runCommand (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/configure/dist/tasks/run.js:34:9)
    at async /Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/configure/dist/index.js:54:13
    at async Command.<anonymous> (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/configure/dist/util/cli.js:31:13)
```

Do you have any suggestions?

Thank you,
Victor

**Comment by mlynch** [comment]
Will test this locally and see what's going on

**Comment by mlynch** [comment]
1) Okay so the `merge` operation isn't currently smart enough to merge each element and compare attributes/etc. I need to think about tweaking the algo here for merge.

2) The inject behavior is expected, it's just a dumb inject so it's not deduping

3) I was able to get this to work using this format of the xpath: `//resources` though I'm not sure why that works and yours doesn't, need to investigate (try this and let me know if it works?)

4) This works fine for me and I'm not getting that error, will investigate a bit more

Try 4.0.1 (no `next`) just to be sure

**Comment by mlynch** [comment]
I started working on updating the merge algorithm and I'd like to get that updated by next week. Follow branch here: https://github.com/ionic-team/trapeze/tree/87-merge-algo

**Comment by vscaiceanu-1a** [comment]
I switched to `4.0.1`.

3. This still doesn't work on my side. `//resources` or `resources`,  I still end up with 8 entries. I also tried  only the delete with no inject and I end up with an error.
```yaml
    xml:
      - file: app/src/main/res/values/strings.xml
        delete: //resources
```

```
updated ios/App/App.xcodeproj/project.pbxproj
updated android/app/src/main/AndroidManifest.xml
updated ios/App/App/Info.plist
updated ios/App/App/capacitor.config.json
updated ios/App/App/ExportOptions.plist
updated android/app/build.gradle
updated android/app/src/main/assets/capacitor.config.json
updated android/app/src/main/res/values/strings.xml
[info] -y provided, automatically applying configuration
Fatal error: Error running command
Error: Expecting token of type --> OPEN <-- but found --> '' <--

    at Object.parse (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/project/node_modules/@prettier/plugin-xml/dist/parser.js:20:27)
    at Object.m [as parse] (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/prettier/standalone.js:40:1354)
    at S (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/prettier/standalone.js:41:15055)
    at D (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/prettier/standalone.js:45:576)
    at /Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/prettier/standalone.js:116:7304
    at Object.format (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/prettier/standalone.js:116:7395)
    at formatXml (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/project/dist/util/xml.js:47:44)
    at writeXml (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/project/dist/util/xml.js:60:29)
    at VFSRef.XmlFile.xmlCommitFn [as commitFn] (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/project/dist/xml.js:22:39)
    at VFSRef.commit (/Users/vscaiceanu/git_clones/capacitor/awesome-app/node_modules/@trapezedev/project/dist/vfs.js:54:21) {
  loc: {
    start: { line: NaN, column: NaN },
    end: { line: NaN, column: NaN }
  },
  codeFrame: ''
}
error Command failed with exit code 1.
```
4. It now works when trying to update only one node. However when trying several nodes, only the last one gets updated.
```yaml
    xml:
      - resFile: values/strings.xml
        target: resources/string[@name="app_name"]
        replace: |
          <string name="app_name">$PRODUCT_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="title_activity_main"]
        replace: |
          <string name="title_activity_main">$PRODUCT_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="package_name"]
        replace: |
          <string name="package_name">$ANDROID_PACKAGE_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="custom_url_scheme"]
        replace: |
          <string name="custom_url_scheme">$ANDROID_PACKAGE_NAME</string>

```

**Comment by mlynch** [comment]
Thanks will get this all working smoothly for you by next release. We're going to go live with the project next week or week after and I want this settled before that

**Comment by golontico** [comment]
I am  here facing the same issue

**Comment by mlynch** [comment]
@golontico stay tuned, making good progress fixing this and it'll be a lot more powerful once I'm done.

**Comment by golontico** [comment]
@mlynch thanks by your hard work i'll try to contribute to the project

**Comment by mlynch** [comment]
I'm making a change to the merge to make it easier to understand. It now will require a matching parent tag, so it'll look like this:

```yaml
 android:
    xml:
      - file: app/src/main/res/values/strings.xml
        target: /resources
        merge: |
          <resources>
            <string name="app_name">$PRODUCT_NAME</string>
            <string name="title_activity_main">$PRODUCT_NAME</string>
            <string name="package_name">$ANDROID_PACKAGE_NAME</string>
            <string name="custom_url_scheme">$ANDROID_PACKAGE_NAME</string>
          </resources>
```

I've got the new algorithm working just need to do some more testing and I'll do a pre-release tomorrow so you all can give it a try

**Comment by mlynch** [comment]
Can you try `5.0.0-next.0@next` and the new merge format above to see how that works for you? Reminder: you need matching target tags to merge the two trees (so both the target and merge above have `resources` as the tag)

**Comment by golontico** [comment]
Thanks @mlynch ill try it

**Comment by vscaiceanu-1a** [comment]
Hi @mlynch 
I'm trying the merge on `5.0.0-next.0` with:

```yaml
    xml:
      - file: app/src/main/res/values/strings.xml
        target: /resources
        merge: |
          <resources>
            <string name="app_name">$PRODUCT_NAME</string>
            <string name="title_activity_main">$PRODUCT_NAME</string>
            <string name="package_name">$ANDROID_PACKAGE_NAME</string>
            <string name="custom_url_scheme">$ANDROID_PACKAGE_NAME</string>
          </resources>
```
I am ending up with a new child `resources` tag

```xml
<?xml version='1.0' encoding='utf-8' ?>
<resources>
    <string name="app_name">Old value</string>
    <string name="title_activity_main">Old value</string>
    <string name="package_name">old.class.path</string>
    <string name="custom_url_scheme">old.class.path</string>
    <resources>
        <string name="app_name">RefX Portal App</string>
        <string name="title_activity_main">RefX Portal App</string>
        <string name="package_name">com.amadeus.des.capacitor.a1a</string>
        <string name="custom_url_scheme">com.amadeus.des.capacitor.a1a</string>
    </resources>
</resources>

```

**Comment by mlynch** [comment]
Hmm weird I’m not seeing that locally, will try some things today

**Comment by vscaiceanu-1a** [comment]
I created a tiny capacitor app to reproduce the issue https://github.com/vscaiceanu-1a/capacitor-playground.

```bash
npm install
npm run build
npm run config
```

**Comment by mlynch** [comment]
Okay weird, must have been a mistake on my part doing the release since it works locally and in the release I just pushed. It must have not built properly before publishing which is something I need to fix for the release process.

Try `5.0.0-next.1`.

**Comment by vscaiceanu-1a** [comment]
Thank you @mlynch. The merge is working smoothly on `5.0.0-next.1`.

However I am still facing the same issues for the delete and the replace (described here: https://github.com/ionic-team/trapeze/issues/87#issuecomment-1191273061)

I updated the sample app with the config for delete & replace.

**Comment by golontico** [comment]
Hi @mlynch and @vscaiceanu-1a..... i try the 5.0.0-next.1 and works great... for me replace all the items

**Comment by mlynch** [comment]
@golontico great! @vscaiceanu-1a I haven't done anything with that yet, will investigate next, thanks for the repro

**Comment by golontico** [comment]
@mlynch a little question this change add some blank spaces to my replace it is ok?

<img width="1142" alt="Captura de Pantalla 2022-07-26 a la(s) 10 15 05" src="https://user-images.githubusercontent.com/3815086/181057696-009cc4b7-fa08-474a-a5c0-a0a88cb2a046.png">

**Comment by mlynch** [comment]
@golontico that's probably a default with prettier which we use to format the code. It *should* be okay but if it's not let me know and I can adjust the defaults. I'm assuming that line is > ~120 chars?

**Comment by golontico** [comment]
@mlynch is a public key.... but is ok thanks for your hard work

**Comment by mlynch** [comment]
The delete stuff not working comes down to the xml file being reloaded every time the operation runs, so I'm making a change to make it use the current file contents as each operation transforms it and this will apply to other operations, too. Kind of a meaningful UX change

**Comment by golontico** [comment]
> The delete stuff not working comes down to the xml file being reloaded every time the operation runs, so I'm making a change to make it use the current file contents as each operation transforms it and this will apply to other operations, too. Kind of a meaningful UX change

hi @mlynch i think this comment it is related to another issue

**Comment by mlynch** [comment]
@golontico that was in reference to the earlier comments not yours

**Comment by mlynch** [comment]
The merge issue and the delete issue and possibly others here are resolved in 5.0.0. Please give it a try and let me know how it works for you.

See the release notes for an explanation on the changes: https://github.com/ionic-team/trapeze/releases/tag/%40trapezedev%2Fconfigure%405.0.0
